services:
  web01:
    build: .
    container_name: web01
    env_file:
      - ./server/.env
    environment:
      - PORT=3000

  web02:
    build: .
    container_name: web02
    env_file:
      - ./server/.env
    environment:
      - PORT=3000

  lb01:
    image: haproxy:2.9-alpine
    container_name: lb01
    depends_on:
      - web01
      - web02
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:80"
